### ISSUE TITLE
Kjøre på?

### ISSUE THREAD

**Issue by kjetilpp** [iotux/ElWiz#12]
Har HomeAssistant som kjører med HassIS på en Pi, kan jeg kjøre dette på den, eller trenger jeg en egen pi?

**Comment by iotux** [comment]
@kjetilpp, I teorien skal det gå bra, men jeg har ikke festet den kombinasjonen. Jeg vil anbefale deg å prøve

**Comment by atxbyea** [comment]
@kjetilpp Du fant vel ut av dette allerede, men HASSOS (Applianceversjonen) kan ikke kjøre tredjeparts software, eller containers som ikke er Add-ons, så det vil nok aldri fungere.

HASSOS er supert for folk som er teknologisk utfordret, men har såpass mange fallgruver og begrensninger at man fort støter på ting som ikke er mulig.

**Comment by iotux** [comment]
@kjetilpp, @atxbyea
På Dockerhub ligger nå "tuxador/elwiz" for 3 forskjellige arkitektuer. Kombinasjonen mosquitto/ElWiz/HA i Docker er testet og kjører på en Raspberry Pi 4 med 4GB RAM.

En fullstendig guide finnes her på Github

**Comment by atxbyea** [comment]
Docker ja, haos nei, det er ikke lov å kjøre container som ikke er add-on på hans :-)
