### ISSUE TITLE
Issues after upgrade

### ISSUE THREAD

**Issue by atxbyea** [iotux/ElWiz#20]
Appears to be reading some fields wrong.

```
11:13:34 2|EU-prices   | fetch-eu-prices: MQTT message published: prices-2023-06-05
11:13:34 0|elwiz       | TypeError: Cannot read properties of undefined (reading 'power')
11:13:34 0|elwiz       |     at Object.calc (/app/ams/amscalc.js:147:42)
11:13:34 0|elwiz       |     at EventEmitter.listHandler (/app/ams/aidon.js:152:23)
11:13:34 0|elwiz       |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
11:13:37 0|elwiz       | TypeError: Cannot read properties of undefined (reading 'power')
11:13:37 0|elwiz       |     at Object.calc (/app/ams/amscalc.js:147:42)
11:13:37 0|elwiz       |     at EventEmitter.listHandler (/app/ams/aidon.js:152:23)
``

**Comment by iotux** [comment]
@atxbyea 
Last update hopefully got rid of a serious memory leak resulting in several issues. This update will probably need more testing before marking it resolved, partly because I don't have access to Aidon AMS meter.

The new configuation variables "amsDebug" and "debugTopic" may help debugging of AMS decoding.
Setting "amsDebug: true" and "debugTopic: debug/hex" will publish HEX output from Tibber Pulse through  MQTT.

**Comment by atxbyea** [comment]
debug/hex/list2
7EA10B41088313FA7CE6E7000F4000000000010C020209060101000281FF0A0B4149444F4E5F5630303031020209060000600100FF0A1037333539393932383931363533353833020209060000600107FF0A0436353235020309060100010700FF06000008C802020F00161B020309060100020700FF060000000002020F00161B020309060100030700FF060000000002020F00161D020309060100040700FF06000001B002020F00161D0203090601001F0700FF10004902020FFF1621020309060100470700FF10005402020FFF1621020309060100200700FF12090202020FFF1623020309060100340700FF12091A02020FFF1623020309060100480700FF12091702020FFF1623BBC97E

debug/hex/list1
7EA02A410883130413E6E7000F40000000000101020309060100010700FF06000008BF02020F00161BB1437E

elwiz/sensor/status
online

pulse/notice
"Debug: Cap voltage critical!"

**Comment by iotux** [comment]
The "Debug: Cap voltage critical" comes from your Tibber Pulse. "Cap" is probably referring to a super (high capacity) Capacitor

**Comment by kimhaak** [comment]
Hi, also got this problem, or similar. Was it fixed? 

kim@ubhome:~/ElWiz$ ./elwiz.js
ElWiz is performing, PID:  522354
UniCache: fetched data from file: ./data/powersave.json
UniCache: retrieved from memory
Data loaded {
  isVirgin: true,
  lastMeterConsumption: 0,
  lastMeterProduction: 0,
  lastMeterConsumptionReactive: 0,
  lastMeterProductionReactive: 0,
  prevDayMeterConsumption: 0,
  prevDayMeterProduction: 0,
  prevDayMeterConsumptionReactive: 0,
  prevDayMeterProductionReactive: 0,
  prevMonthMeterConsumption: 0,
  prevMonthMeterProduction: 0,
  accumulatedCost: 0,
  accumulatedReward: 0,
  minPower: 9999999,
  maxPower: 0,
  averagePower: 0
}
Connected to MQTT broker...
/home/kim/ElWiz/ams/amscalc.js:158
    obj.minPower = await getMinPower(obj.power);
                                         ^

TypeError: Cannot read properties of undefined (reading 'power')
    at Object.calc (/home/kim/ElWiz/ams/amscalc.js:158:42)
    at EventEmitter.listHandler (/home/kim/ElWiz/ams/aidon.js:153:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.17.1

**Comment by iotux** [comment]
> Hi, also got this problem, or similar. Was it fixed?
> 
> kim@ubhome:~/ElWiz$ ./elwiz.js ElWiz is performing, PID: 522354 UniCache: fetched data from file: ./data/powersave.json UniCache: retrieved from memory Data loaded { isVirgin: true, lastMeterConsumption: 0, lastMeterProduction: 0, lastMeterConsumptionReactive: 0, lastMeterProductionReactive: 0, prevDayMeterConsumption: 0, prevDayMeterProduction: 0, prevDayMeterConsumptionReactive: 0, prevDayMeterProductionReactive: 0, prevMonthMeterConsumption: 0, prevMonthMeterProduction: 0, accumulatedCost: 0, accumulatedReward: 0, minPower: 9999999, maxPower: 0, averagePower: 0 } Connected to MQTT broker... /home/kim/ElWiz/ams/amscalc.js:158 obj.minPower = await getMinPower(obj.power); ^
> 
> TypeError: Cannot read properties of undefined (reading 'power') at Object.calc (/home/kim/ElWiz/ams/amscalc.js:158:42) at EventEmitter.listHandler (/home/kim/ElWiz/ams/aidon.js:153:23) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> Node.js v18.17.1

This error apparently comes from the AMS decoder. It seems that  you have an aidon meter, which I unforunately don't have. This makes impossible to test without having access to your Tibber Pulse.

However, you can use this ElWiz companion program to relay the output from your Pulse to another broker.

https://github.com/iotux/mqtt-relay

Download or clone this program and configure the input broker according to your needs.
For the output broker you will need the correct credentials and broker URL.

Unfortunately, I have not yet esablished any routine other than by email.

To progress further, I will need your email address, and I will send the needed information.

If you are not comfortable with this, you can alternatively use discord if you have an account on any discord server. Then I will need a link and your nick to write you a PM.

As soon as we have established contact, I will delete this post.

**Comment by kimhaak** [comment]
> > Hi, also got this problem, or similar. Was it fixed?
> > kim@ubhome:~/ElWiz$ ./elwiz.js ElWiz is performing, PID: 522354 UniCache: fetched data from file: ./data/powersave.json UniCache: retrieved from memory Data loaded { isVirgin: true, lastMeterConsumption: 0, lastMeterProduction: 0, lastMeterConsumptionReactive: 0, lastMeterProductionReactive: 0, prevDayMeterConsumption: 0, prevDayMeterProduction: 0, prevDayMeterConsumptionReactive: 0, prevDayMeterProductionReactive: 0, prevMonthMeterConsumption: 0, prevMonthMeterProduction: 0, accumulatedCost: 0, accumulatedReward: 0, minPower: 9999999, maxPower: 0, averagePower: 0 } Connected to MQTT broker... /home/kim/ElWiz/ams/amscalc.js:158 obj.minPower = await getMinPower(obj.power); ^
> > TypeError: Cannot read properties of undefined (reading 'power') at Object.calc (/home/kim/ElWiz/ams/amscalc.js:158:42) at EventEmitter.listHandler (/home/kim/ElWiz/ams/aidon.js:153:23) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> > Node.js v18.17.1
> 
> This error apparently comes from the AMS decoder. It seems that you have an aidon meter, which I unforunately don't have. This makes impossible to test without having access to your Tibber Pulse.
> 
> However, you can use this ElWiz companion program to relay the output from your Pulse to another broker.
> 
> https://github.com/iotux/mqtt-relay
> 
> Download or clone this program and configure the input broker according to your needs. For the output broker you will need the correct credentials and broker URL.
> 
> Unfortunately, I have not yet esablished any routine other than by email.
> 
> To progress further, I will need your email address, and I will send the needed information.
> 
> If you are not comfortable with this, you can alternatively use discord if you have an account on any discord server. Then I will need a link and your nick to write you a PM.
> 
> As soon as we have established contact, I will delete this post.

Hi,

You could reach me at discord - kimhaak

**Comment by iotux** [comment]
@kimhaak I am afraid that I will need an invite link. Cannot find yours

**Comment by kimhaak** [comment]
Sooo - i may be too old for discord stuff, cant seem to find an invite to be "friends" , but i made my own server and here is the link 📦 

https://discord.gg/PBH5pr6B
