### ISSUE TITLE
any idea to decode this payload from my tibber pulse

### ISSUE THREAD

**Issue by jynis** [iotux/ElWiz#29]
Hi,

Got me a tibber pulse last week and manage to set it up through my own mqtt-broker and bridge it to tibber cloud.
Everything looked good until tibber pulse after few hours switched over to binary payload.

Now I'm struggling with decoding the payload and asking for some ideas/pointers to solve it. Current Elwiz fails on dataLength calculation right now.

Payload is like this:

08dcd9021801129102097748e40a00000000120250311afe01384f74ce3b0e02310c04d07ea5dc039030e34f7e74144043cd5e01898efb1718d8440189769e3ce3dde57c8a474d085398b0c59e09849518b324362b11f33a4cfc96e202c0925621b1bab9cfb705a52152d548600ca81d81cc94e1783d3c1a5b633635a1acdfec071f16b2a85edb2797dc1f7e35b65c7f72afea435d4a8aa3481f71820d23ff56ec492719e30008c2507437f110ae0c4d684bd15112afe0fd8f2220d492c8fa9a97f6ff548ddc1899b34a825f43cc0ef1c10c6606cea3a0c9c28443cab9c5c6c2b0db91cc2d31968f436ff49e9edf05d0dd0d8606e90052183f7828a45e495eeeceae77c8c00acbdb548820156ec95f695d1e000000ffff20c005126c098970e40a00000000120250311a5ad227907e2d0d70a65f53335aa55f635ce9d7d4c0885ae9d7c40c67fa054991987ecd494ebf16544cbf4628698ae8f48b92ea894dbf6628a91e9e7e0d9052253cfd5a2009124abf96d8d2af299ef46bea646ecacb05000000ffff20c005

BR // Jyrki

**Comment by jynis** [comment]
Just to complement my post. 
I'm located in Sweden and meter is a Landis+Gyr E360

**Comment by iotux** [comment]
@jynis, 
Sign in to the ElWiz discord where it's more convenient to discuss the matter. Here is an invite link:
https://discord.gg/AYZGmtUx

**Comment by jynis** [comment]
Moved to discord
