### ISSUE TITLE
Username and password

### ISSUE THREAD

**Issue by tmjo** [iotux/ElWiz#3]
Hi! Great work here, just got my Pulse up and running with the information on your site + the Home Assistant custom integration [AMS HAN](https://github.com/toreamun/amshan-homeassistant) which refers to your guide.

This may be obvious for some, but I was struggling a bit to connect to my local MQTT-broker at first since I have authentication required to connect to it. Got a tip in this [thread ](https://www.hjemmeautomasjon.no/forums/topic/4255-tibber-pulse-mqtt/?&page=4#comments) to use: 

`username:password@host`

and it worked well. Since this may not be obvious to everyone, it would be great if this was included in your guide!

Thanks for your work!

**Comment by iotux** [comment]
README.md updated
