### ISSUE TITLE
Any plans on publishing the docker images anywhere?

### ISSUE THREAD

**Issue by brujoand** [iotux/ElWiz#6]
I'm writing a deployment of ElWiz to my k8s cluster, and currently I'm just building the image locally. Would be nice to have image generation linked to this repo to catch updates. 

ref: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages

**Comment by iotux** [comment]
> I'm writing a deployment of ElWiz to my k8s cluster, and currently I'm just buildign the image locally. Would be nice to have image generation linked to this repo to catch updates.
> 
> ref: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages

Kontakt meg via PM på <https://hjemmeautomasjon.no>

**Comment by stenkarlsen** [comment]
+1!

**Comment by alekslyse** [comment]
+1

**Comment by atxbyea** [comment]
It is already published at `tuxador/elwiz` so I guess this can also be closed

**Comment by iotux** [comment]
Docker images now available at Dockerhub https://hub.docker.com/repository/docker/tuxador/elwiz/tags
for amd64, arm64 and arm/v7 as **tuxador/elwiz:latest**
